name: React CI/CD with Serve and PM2

on:
  push:
    branches:
      - main # or the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Serve React App
        run: |
          npm install -g serve
          serve -l 5173 -s build &

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Install PM2
        run: npm install pm2 -g

      - name: Stop Existing PM2 Process
        run: pm2 delete reactProject || true

      - name: Start PM2 Process
        run: pm2 serve build --name reactProject --no-daemon
